// AUTO-GENERATED by goldfish_prep.mjs
window.GOLDFISH_DATA = {
  "meta": {
    "generated": "2026-06-11T14:00:00Z"
  },
  "ggbr": {
    "supply": 25000000,
    "backingUsd": 104211250,
    "price": 4.172,
    "marketCapUsd": 104301211,
    "ionAuCollateralOz": 25000,
    "defiTvlUsd": 6200000,
    "stakedUsd": 1300000,
    "source": "dune.com/goldfishgold_main/goldfishgold-protocol-analysis"
  },
  "rwaPartners": {
    "curators": [
      {
        "name": "Gauntlet",
        "rwaUsd": 15317908.500198798,
        "aumUsd": 698991420.98399,
        "verified": true,
        "holds": [
          "AA_FalconXUSDC",
          "SPYon",
          "QQQon"
        ],
        "site": "https://www.gauntlet.xyz/",
        "twitter": "https://x.com/gauntlet_xyz",
        "forum": "https://forum.morpho.org/c/vaults/gauntlet/19"
      },
      {
        "name": "Steakhouse Financial",
        "rwaUsd": 6664192.842890743,
        "aumUsd": 1047739796.3117322,
        "verified": true,
        "holds": [
          "XAUt",
          "FLHYon",
          "mF-ONE",
          "USCC",
          "AA_FalconXUSDC",
          "deSPXA",
          "EUTBL",
          "XAUt0"
        ],
        "site": "https://www.steakhouse.financial",
        "twitter": "https://x.com/SteakhouseFi",
        "forum": "https://forum.morpho.org/c/vaults/steakhouse-financial/18"
      },
      {
        "name": "Hyperithm",
        "rwaUsd": 2827810.04612296,
        "aumUsd": 3770606.4615250495,
        "verified": true,
        "holds": [
          "mHyperBTC",
          "mHYPER"
        ],
        "site": "https://www.hyperithm.com/",
        "twitter": "https://x.com/hyperithm",
        "forum": "https://forum.morpho.org/c/vaults/hyperithm/38"
      },
      {
        "name": "MEV Capital",
        "rwaUsd": 1281514.466465858,
        "aumUsd": 8955775.705791045,
        "verified": true,
        "holds": [
          "mF-ONE",
          "mHYPER"
        ],
        "site": "https://mevcapital.com/",
        "twitter": "https://x.com/MEVCapital",
        "forum": "https://forum.morpho.org/c/vaults/mev-capital/30"
      },
      {
        "name": "Felix",
        "rwaUsd": 416683.58641347155,
        "aumUsd": 49940548.30815263,
        "verified": true,
        "holds": [
          "thBILL"
        ],
        "site": "https://www.usefelix.xyz/",
        "twitter": "https://x.com/felixprotocol",
        "forum": null
      },
      {
        "name": "Clearstar",
        "rwaUsd": 258177.96208044817,
        "aumUsd": 10465772.173115103,
        "verified": true,
        "holds": [
          "mF-ONE",
          "AA_FalconXUSDC",
          "mBASIS"
        ],
        "site": "https://www.clearstar.xyz/",
        "twitter": "https://x.com/ClearstarLabs",
        "forum": "https://forum.morpho.org/c/vaults/clearstar-labs/40"
      },
      {
        "name": "UltraYield",
        "rwaUsd": 12660.567979008132,
        "aumUsd": 878487.3888462683,
        "verified": true,
        "holds": [
          "mBASIS"
        ],
        "site": "https://ultrayield.app/",
        "twitter": "https://x.com/ultrayieldapp",
        "forum": "https://forum.morpho.org/c/vaults/ultrayield/44"
      }
    ],
    "funds": [
      {
        "name": "3jane",
        "what": "Credit yieldcoin (USD3 / sUSD3) — senior + leveraged tranching of credit pools",
        "collateral": "Fintech receivables, consumer/SMB loans, warehouse facilities",
        "backers": "Paradigm, Wintermute, Coinbase Ventures",
        "fit": "High",
        "site": "https://3jane.xyz",
        "twitter": "https://x.com/3janexyz",
        "note": "Tranching expertise — could structure a GGBR senior/junior split"
      },
      {
        "name": "Centrifuge",
        "what": "RWA tokenization platform — tokenized Janus Henderson AAA CLO (JAAA)",
        "collateral": "AAA CLOs ($27B ETF mirror, $1B Sky-seeded), institutional credit",
        "backers": "—",
        "fit": "High",
        "site": "https://centrifuge.io",
        "twitter": "https://x.com/centrifuge",
        "note": "Already tokenizes institutional credit — natural structurer for GGBR"
      },
      {
        "name": "Maple Finance",
        "what": "Institutional private credit — syrupUSDC / syrupUSDT",
        "collateral": "Overcollateralized institutional loans",
        "backers": "—",
        "fit": "High",
        "site": "https://maple.finance",
        "twitter": "https://x.com/maplefinance",
        "note": "Largest on-chain private credit (~$76M on Morpho via Sentora)"
      },
      {
        "name": "Midas",
        "what": "Tokenized RWA issuer — mF-ONE, mBASIS, mHYPER, mTBILL",
        "collateral": "Treasuries, structured credit",
        "backers": "—",
        "fit": "Med-High",
        "site": "https://midas.app",
        "twitter": "https://x.com/MidasRWA",
        "note": "Already in MEV Capital / Clearstar / Hyperithm vaults"
      },
      {
        "name": "Superstate",
        "what": "Tokenized treasuries & credit — USTB, USCC",
        "collateral": "T-bills, carry/credit",
        "backers": "—",
        "fit": "Med",
        "site": "https://superstate.co",
        "twitter": "https://x.com/superstatefunds",
        "note": "Institutional RWA, held by Steakhouse"
      },
      {
        "name": "Ondo Finance",
        "what": "Tokenized treasuries & equities — USDY, SPYon, QQQon",
        "collateral": "T-bills, tokenized stocks",
        "backers": "—",
        "fit": "Med",
        "site": "https://ondo.finance",
        "twitter": "https://x.com/OndoFinance",
        "note": "Tokenized-RWA issuer, held by Gauntlet"
      }
    ]
  },
  "activation": {
    "backingUsd": 104211250,
    "defiTvlUsd": 6200000,
    "dormantUsd": 98011250,
    "activatedPct": 5.949453633844715,
    "tokGoldTotalUsd": 4495126306,
    "ggbrSharePct": 2.318316392153453
  },
  "demand": {
    "tokGold": {
      "XAUt": 2572871214,
      "PAXG": 1922255092,
      "goldOz": 4207.37
    },
    "tokGoldTotalUsd": 4495126306,
    "goldCollateralUsd": 62476376,
    "idleUsd": 4432649930,
    "categoryActivationPct": 1.3898691993728374,
    "byProtocol": {
      "Aave": 47511414,
      "Morpho": 8153629,
      "Fluid": 6497092,
      "Compound": 314241
    },
    "pools": [
      {
        "protocol": "Aave",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 40043991
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 7176189
      },
      {
        "protocol": "Aave",
        "symbol": "XAUT0",
        "chain": "Plasma",
        "tvlUsd": 4333048
      },
      {
        "protocol": "Aave",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 3134375
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG-XAUT",
        "chain": "Ethereum",
        "tvlUsd": 2812387
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 1789048
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 598276
      },
      {
        "protocol": "Morpho",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 527949
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 425460
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT0",
        "chain": "Plasma",
        "tvlUsd": 425153
      },
      {
        "protocol": "Compound",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 314241
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Monad",
        "tvlUsd": 295257
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 251391
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 100526
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT0",
        "chain": "Plasma",
        "tvlUsd": 84285
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Monad",
        "tvlUsd": 68746
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 41994
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Arbitrum",
        "tvlUsd": 24987
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Arbitrum",
        "tvlUsd": 18507
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 10566
      }
    ],
    "venues": [
      {
        "venue": "Aave v3 / v4",
        "governance": "DAO-governed (risk: Gauntlet, Chaos Labs)",
        "usd": 47511414
      },
      {
        "venue": "Morpho",
        "governance": "Permissionless markets — borrower-posted",
        "usd": 8153629
      },
      {
        "venue": "Fluid",
        "governance": "Protocol-governed",
        "usd": 6497092
      },
      {
        "venue": "Compound v3",
        "governance": "Protocol-governed",
        "usd": 314241
      }
    ],
    "venueCount": 4,
    "vaultCuration": [
      {
        "curator": "Direct / unregistered",
        "usd": 104652.365732257,
        "named": false
      },
      {
        "curator": "Steakhouse Financial",
        "usd": 947.1467122645006,
        "named": true
      }
    ],
    "vaultSupplyTotalUsd": 105599.5124445215,
    "fundCuratedUsd": 947.1467122645006,
    "curatorCapacityUsd": 65479969.70311971,
    "curatorDeployedUsd": 947.1467122645006,
    "enabledMarkets": [
      {
        "curator": "August Digital",
        "vault": "August USDC",
        "market": "XAUt0/USDC",
        "capUsd": 19996104.14889542,
        "deployedUsd": 0
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield USDC",
        "market": "XAUt0/USDC",
        "capUsd": 19995990.665944204,
        "deployedUsd": 731.9164127106777
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse USDT",
        "market": "XAUt/USDT",
        "capUsd": 9994252.335755644,
        "deployedUsd": 1.1424689695563008
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield USDC",
        "market": "XAUt0/USDC",
        "capUsd": 4999026.037223855,
        "deployedUsd": 0
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield AUSD",
        "market": "XAUt0/AUSD",
        "capUsd": 4998969.3510289965,
        "deployedUsd": 91.53860827528392
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield USDT0",
        "market": "XAUt0/USDT0",
        "capUsd": 4995914.547483809,
        "deployedUsd": 122.5492223089827
      },
      {
        "curator": "SingularV",
        "vault": "SingularV USDT",
        "market": "XAUt/USDT",
        "capUsd": 499712.61678778223,
        "deployedUsd": 0
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse PYUSD",
        "market": "PAXG/PYUSD",
        "capUsd": 0,
        "deployedUsd": 0
      }
    ],
    "readyCurators": [
      {
        "curator": "Steakhouse Financial",
        "capUsd": 44984152.937436506,
        "deployedUsd": 947.1467122645006,
        "markets": 6
      },
      {
        "curator": "August Digital",
        "capUsd": 19996104.14889542,
        "deployedUsd": 0,
        "markets": 1
      },
      {
        "curator": "SingularV",
        "capUsd": 499712.61678778223,
        "deployedUsd": 0,
        "markets": 1
      }
    ],
    "morphoProductiveUsd": 3900312.329437272,
    "morphoBorrowUsd": 3314934.834234645,
    "markets": [
      {
        "market": "PAXG/USDC",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 1220274246.9104772,
        "borrowUsd": 1220274246.9104772,
        "collateralUsd": 245.5757265446864,
        "util": 100,
        "ghost": true
      },
      {
        "market": "XAUt/USDT",
        "collateral": "XAUt",
        "chain": "Ethereum",
        "supplyUsd": 3270052.439559439,
        "borrowUsd": 2798004.629301222,
        "collateralUsd": 7175027.502619416,
        "util": 85.56451864356603,
        "ghost": false
      },
      {
        "market": "PAXG/PYUSD",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 327323.080814386,
        "borrowUsd": 295162.03603148676,
        "collateralUsd": 527924.1524616963,
        "util": 90.17452582235205,
        "ghost": false
      },
      {
        "market": "XAUt0/USDC",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 180508.7999320344,
        "borrowUsd": 162079.18266070678,
        "collateralUsd": 295257.09358962224,
        "util": 89.79018348231953,
        "ghost": false
      },
      {
        "market": "XAUt0/USDT0",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 61932.69719791315,
        "borrowUsd": 36528.93065566259,
        "collateralUsd": 68746.24462182753,
        "util": 58.981656392147976,
        "ghost": false
      },
      {
        "market": "XAUt/tGBP",
        "collateral": "XAUt",
        "chain": "Ethereum",
        "supplyUsd": 18704.754679263515,
        "borrowUsd": 1.2559287131055095,
        "collateralUsd": 41987.65038312738,
        "util": 0.0067144890945715,
        "ghost": false
      },
      {
        "market": "PAXG/tGBP",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 15033.889314489319,
        "borrowUsd": 0.9160860851825211,
        "collateralUsd": 3.4712248298807027,
        "util": 0.0060934736582077,
        "ghost": false
      },
      {
        "market": "XAUt0/USDT0",
        "collateral": "XAUt0",
        "chain": "Arbitrum One",
        "supplyUsd": 12937.277261194467,
        "borrowUsd": 10658.686511860358,
        "collateralUsd": 24948.522929545696,
        "util": 82.38740112520607,
        "ghost": false
      },
      {
        "market": "XAUt0/USDC",
        "collateral": "XAUt0",
        "chain": "Arbitrum One",
        "supplyUsd": 10183.394126235218,
        "borrowUsd": 9178.357849941101,
        "collateralUsd": 18478.46077225264,
        "util": 90.13063558342628,
        "ghost": false
      },
      {
        "market": "XAUt0/AUSD",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 3447.043769083942,
        "borrowUsd": 3320.8392089674194,
        "collateralUsd": 7832.699781373706,
        "util": 96.33875956991223,
        "ghost": false
      },
      {
        "market": "rXAUt/USDC",
        "collateral": "rXAUt",
        "chain": "World Chain",
        "supplyUsd": 188.9527832334887,
        "borrowUsd": 0,
        "collateralUsd": 0,
        "util": 0,
        "ghost": false
      }
    ]
  },
  "leads": [
    {
      "name": "Gauntlet",
      "aumUsd": 698991420.98399,
      "verified": true,
      "rwaUsd": 15317908.500198798,
      "holds": [
        "AA_FalconXUSDC",
        "SPYon",
        "QQQon"
      ],
      "goldActive": false
    },
    {
      "name": "Steakhouse Financial",
      "aumUsd": 1047739796.3117322,
      "verified": true,
      "rwaUsd": 6664192.842890743,
      "holds": [
        "XAUt",
        "FLHYon",
        "mF-ONE",
        "USCC",
        "AA_FalconXUSDC",
        "deSPXA",
        "EUTBL",
        "XAUt0"
      ],
      "goldActive": true
    },
    {
      "name": "Hyperithm",
      "aumUsd": 3770606.4615250495,
      "verified": true,
      "rwaUsd": 2827810.04612296,
      "holds": [
        "mHyperBTC",
        "mHYPER"
      ],
      "goldActive": false
    },
    {
      "name": "MEV Capital",
      "aumUsd": 8955775.705791045,
      "verified": true,
      "rwaUsd": 1281514.466465858,
      "holds": [
        "mF-ONE",
        "mHYPER"
      ],
      "goldActive": false
    },
    {
      "name": "Felix",
      "aumUsd": 49940548.30815263,
      "verified": true,
      "rwaUsd": 416683.58641347155,
      "holds": [
        "thBILL"
      ],
      "goldActive": false
    },
    {
      "name": "Clearstar",
      "aumUsd": 10465772.173115103,
      "verified": true,
      "rwaUsd": 258177.96208044817,
      "holds": [
        "mF-ONE",
        "AA_FalconXUSDC",
        "mBASIS"
      ],
      "goldActive": false
    },
    {
      "name": "UltraYield",
      "aumUsd": 878487.3888462683,
      "verified": true,
      "rwaUsd": 12660.567979008132,
      "holds": [
        "mBASIS"
      ],
      "goldActive": false
    }
  ]
};
