// AUTO-GENERATED by goldfish_prep.mjs
window.GOLDFISH_DATA = {
  "meta": {
    "generated": "2026-06-11T17:00:00Z"
  },
  "ggbr": {
    "price": 4.230572221971105,
    "circSupply": 5717206.2854594765,
    "circMcapUsd": 24177245,
    "totalSupply": 25000000,
    "fdvUsd": 105721412,
    "backingUsd": 104211250,
    "defiTvlUsd": 6200000,
    "stakedUsd": 1300000,
    "source": "CoinGecko/DefiLlama (market) + Dune goldfishgold_main (TVL, backing)"
  },
  "rwaPartners": {
    "curators": [
      {
        "name": "Gauntlet",
        "rwaUsd": 15317908.500198798,
        "aumUsd": 698991420.98399,
        "verified": true,
        "holds": [
          "AA_FalconXUSDC",
          "SPYon",
          "QQQon"
        ],
        "site": "https://www.gauntlet.xyz/",
        "twitter": "https://x.com/gauntlet_xyz",
        "forum": "https://forum.morpho.org/c/vaults/gauntlet/19"
      },
      {
        "name": "Steakhouse Financial",
        "rwaUsd": 6664192.842890743,
        "aumUsd": 1047739796.3117322,
        "verified": true,
        "holds": [
          "XAUt",
          "FLHYon",
          "mF-ONE",
          "USCC",
          "AA_FalconXUSDC",
          "deSPXA",
          "EUTBL",
          "XAUt0"
        ],
        "site": "https://www.steakhouse.financial",
        "twitter": "https://x.com/SteakhouseFi",
        "forum": "https://forum.morpho.org/c/vaults/steakhouse-financial/18"
      },
      {
        "name": "Hyperithm",
        "rwaUsd": 2827810.04612296,
        "aumUsd": 3770606.4615250495,
        "verified": true,
        "holds": [
          "mHyperBTC",
          "mHYPER"
        ],
        "site": "https://www.hyperithm.com/",
        "twitter": "https://x.com/hyperithm",
        "forum": "https://forum.morpho.org/c/vaults/hyperithm/38"
      },
      {
        "name": "MEV Capital",
        "rwaUsd": 1281514.466465858,
        "aumUsd": 8955775.705791045,
        "verified": true,
        "holds": [
          "mF-ONE",
          "mHYPER"
        ],
        "site": "https://mevcapital.com/",
        "twitter": "https://x.com/MEVCapital",
        "forum": "https://forum.morpho.org/c/vaults/mev-capital/30"
      },
      {
        "name": "Felix",
        "rwaUsd": 416683.58641347155,
        "aumUsd": 49940548.30815263,
        "verified": true,
        "holds": [
          "thBILL"
        ],
        "site": "https://www.usefelix.xyz/",
        "twitter": "https://x.com/felixprotocol",
        "forum": null
      },
      {
        "name": "Clearstar",
        "rwaUsd": 258177.96208044817,
        "aumUsd": 10465772.173115103,
        "verified": true,
        "holds": [
          "mF-ONE",
          "AA_FalconXUSDC",
          "mBASIS"
        ],
        "site": "https://www.clearstar.xyz/",
        "twitter": "https://x.com/ClearstarLabs",
        "forum": "https://forum.morpho.org/c/vaults/clearstar-labs/40"
      },
      {
        "name": "UltraYield",
        "rwaUsd": 12660.567979008132,
        "aumUsd": 878487.3888462683,
        "verified": true,
        "holds": [
          "mBASIS"
        ],
        "site": "https://ultrayield.app/",
        "twitter": "https://x.com/ultrayieldapp",
        "forum": "https://forum.morpho.org/c/vaults/ultrayield/44"
      }
    ],
    "tranchers": [
      {
        "name": "Maple",
        "star": false,
        "x": "https://x.com/maplefinance",
        "site": "https://maple.finance",
        "tvlUsd": 3986124376,
        "poolCount": 2,
        "seniorSym": "USDT",
        "seniorApy": 4.38432,
        "juniorSym": "USDC",
        "juniorApy": 4.76901,
        "spreadPct": 0.38469,
        "chains": [
          "Ethereum"
        ],
        "fees30dUsd": 8922664
      },
      {
        "name": "Centrifuge",
        "star": false,
        "x": "https://x.com/centrifuge",
        "site": "https://centrifuge.io",
        "tvlUsd": 1627925375,
        "poolCount": 19,
        "seniorSym": "USDC",
        "seniorApy": 0,
        "juniorSym": "USDC",
        "juniorApy": 4.09362,
        "spreadPct": 4.09362,
        "chains": [
          "Ethereum",
          "Avalanche",
          "Base",
          "Plume Mainnet",
          "Pharos",
          "Monad",
          "BSC",
          "OP Mainnet"
        ],
        "fees30dUsd": 4384184
      },
      {
        "name": "3jane",
        "star": true,
        "x": "https://x.com/3janexyz",
        "site": "https://3jane.xyz",
        "tvlUsd": 37463246,
        "poolCount": 2,
        "seniorSym": "USD3",
        "seniorApy": 3.29377,
        "juniorSym": "SUSD3",
        "juniorApy": 19.11688,
        "spreadPct": 15.823109999999998,
        "chains": [
          "Ethereum"
        ],
        "fees30dUsd": 23080
      },
      {
        "name": "Goldfinch",
        "star": false,
        "x": "https://x.com/goldfinch_fi",
        "site": "https://goldfinch.finance",
        "tvlUsd": 36718977,
        "poolCount": 1,
        "seniorSym": "USDC",
        "seniorApy": 10.1233,
        "juniorSym": "USDC",
        "juniorApy": 10.1233,
        "spreadPct": 0,
        "chains": [
          "Ethereum"
        ],
        "fees30dUsd": 97342
      },
      {
        "name": "Clearpool",
        "star": false,
        "x": "https://x.com/ClearpoolFin",
        "site": "https://clearpool.finance",
        "tvlUsd": 28255269,
        "poolCount": 4,
        "seniorSym": "USDC",
        "seniorApy": 0,
        "juniorSym": "USDT",
        "juniorApy": 12.56479,
        "spreadPct": 12.56479,
        "chains": [
          "Flare",
          "Ethereum",
          "Mantle"
        ],
        "fees30dUsd": 79070
      },
      {
        "name": "Credix",
        "star": false,
        "x": "https://x.com/credixfinance",
        "site": "https://credix.finance",
        "tvlUsd": 13529316,
        "poolCount": 1,
        "seniorSym": "USDC",
        "seniorApy": 0.11494,
        "juniorSym": "USDC",
        "juniorApy": 0.11494,
        "spreadPct": 0,
        "chains": [
          "Solana"
        ],
        "fees30dUsd": 0
      },
      {
        "name": "Wildcat",
        "star": false,
        "x": "https://x.com/WildcatFi",
        "site": "https://wildcat.finance",
        "tvlUsd": 6781916,
        "poolCount": 32,
        "seniorSym": "WMTWETH",
        "seniorApy": 3.75,
        "juniorSym": "KPHOENIXUSDC",
        "juniorApy": 50,
        "spreadPct": 46.25,
        "chains": [
          "Ethereum"
        ],
        "fees30dUsd": 1636821
      },
      {
        "name": "TrueFi",
        "star": false,
        "x": "https://x.com/TrueFiDAO",
        "site": "https://truefi.io",
        "tvlUsd": 21727.022018303483,
        "poolCount": 0,
        "seniorSym": null,
        "seniorApy": null,
        "juniorSym": null,
        "juniorApy": null,
        "spreadPct": null,
        "chains": [],
        "fees30dUsd": 0
      },
      {
        "name": "Qiro",
        "star": false,
        "x": "https://x.com/QiroFinance",
        "site": "https://qiro.fi",
        "tvlUsd": null,
        "poolCount": 0,
        "seniorSym": null,
        "seniorApy": null,
        "juniorSym": null,
        "juniorApy": null,
        "spreadPct": null,
        "chains": [],
        "fees30dUsd": 0
      }
    ],
    "issuers": [
      {
        "name": "Midas",
        "what": "mF-ONE / mBASIS / mHYPER / mTBILL",
        "site": "https://midas.app"
      },
      {
        "name": "Superstate",
        "what": "USTB / USCC",
        "site": "https://superstate.co"
      },
      {
        "name": "Ondo Finance",
        "what": "USDY / SPYon / QQQon",
        "site": "https://ondo.finance"
      }
    ]
  },
  "activation": {
    "circMcapUsd": 24177245,
    "fdvUsd": 105721412,
    "priceUsd": 4.230572221971105,
    "circSupply": 5717206.2854594765,
    "totalSupply": 25000000,
    "defiTvlUsd": 6200000,
    "activatedPct": 25.643947439007214,
    "idleCircUsd": 17977245,
    "unissuedUsd": 81544167,
    "backingUsd": 104211250,
    "tokGoldTotalUsd": 4498582378,
    "ggbrSharePct": 0.5374414197289598
  },
  "demand": {
    "tokGold": {
      "XAUt": 2574136456,
      "PAXG": 1924445922,
      "goldOz": 4211.37
    },
    "tokGoldTotalUsd": 4498582378,
    "goldCollateralUsd": 62571027,
    "idleUsd": 4436011351,
    "categoryActivationPct": 1.3909054395891292,
    "byProtocol": {
      "Aave": 47580545,
      "Morpho": 8169958,
      "Fluid": 6505934,
      "Compound": 314590
    },
    "pools": [
      {
        "protocol": "Aave",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 40088053
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 7187971
      },
      {
        "protocol": "Aave",
        "symbol": "XAUT0",
        "chain": "Plasma",
        "tvlUsd": 4345889
      },
      {
        "protocol": "Aave",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 3146603
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG-XAUT",
        "chain": "Ethereum",
        "tvlUsd": 2815441
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 1791607
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 599118
      },
      {
        "protocol": "Morpho",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 528900
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT0",
        "chain": "Plasma",
        "tvlUsd": 426413
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 425932
      },
      {
        "protocol": "Compound",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 314590
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Monad",
        "tvlUsd": 296132
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 251670
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 100637
      },
      {
        "protocol": "Fluid",
        "symbol": "XAUT0",
        "chain": "Plasma",
        "tvlUsd": 84535
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Monad",
        "tvlUsd": 71383
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT",
        "chain": "Ethereum",
        "tvlUsd": 42066
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Arbitrum",
        "tvlUsd": 24994
      },
      {
        "protocol": "Morpho",
        "symbol": "XAUT0",
        "chain": "Arbitrum",
        "tvlUsd": 18512
      },
      {
        "protocol": "Fluid",
        "symbol": "PAXG",
        "chain": "Ethereum",
        "tvlUsd": 10581
      }
    ],
    "venues": [
      {
        "venue": "Aave v3 / v4",
        "governance": "DAO-governed (risk: Gauntlet, Chaos Labs)",
        "usd": 47580545
      },
      {
        "venue": "Morpho",
        "governance": "Permissionless markets — borrower-posted",
        "usd": 8169958
      },
      {
        "venue": "Fluid",
        "governance": "Protocol-governed",
        "usd": 6505934
      },
      {
        "venue": "Compound v3",
        "governance": "Protocol-governed",
        "usd": 314590
      }
    ],
    "venueCount": 4,
    "vaultCuration": [
      {
        "curator": "Direct / unregistered",
        "usd": 104658.0619560374,
        "named": false
      },
      {
        "curator": "Steakhouse Financial",
        "usd": 3803.748612546484,
        "named": true
      }
    ],
    "vaultSupplyTotalUsd": 108461.81056858388,
    "fundCuratedUsd": 3803.748612546484,
    "curatorCapacityUsd": 65479880.119732544,
    "curatorDeployedUsd": 3803.748612546484,
    "enabledMarkets": [
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield USDC",
        "market": "XAUt0/USDC",
        "capUsd": 19996551.166198432,
        "deployedUsd": 670.4836727212734
      },
      {
        "curator": "August Digital",
        "vault": "August USDC",
        "market": "XAUt0/USDC",
        "capUsd": 19995447.49294954,
        "deployedUsd": 0
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse USDT",
        "market": "XAUt/USDT",
        "capUsd": 9994322.671976823,
        "deployedUsd": 3116.7109787913905
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield USDC",
        "market": "XAUt0/USDC",
        "capUsd": 4998861.873237385,
        "deployedUsd": 0
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield AUSD",
        "market": "XAUt0/AUSD",
        "capUsd": 4998818.6990624005,
        "deployedUsd": 16.55396103382009
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse High Yield USDT0",
        "market": "XAUt0/USDT0",
        "capUsd": 4996162.0827091215,
        "deployedUsd": 0
      },
      {
        "curator": "SingularV",
        "vault": "SingularV USDT",
        "market": "XAUt/USDT",
        "capUsd": 499716.1335988412,
        "deployedUsd": 0
      },
      {
        "curator": "Steakhouse Financial",
        "vault": "Steakhouse PYUSD",
        "market": "PAXG/PYUSD",
        "capUsd": 0,
        "deployedUsd": 0
      }
    ],
    "readyCurators": [
      {
        "curator": "Steakhouse Financial",
        "capUsd": 44984716.49318416,
        "deployedUsd": 3803.748612546484,
        "markets": 6
      },
      {
        "curator": "August Digital",
        "capUsd": 19995447.49294954,
        "deployedUsd": 0,
        "markets": 1
      },
      {
        "curator": "SingularV",
        "capUsd": 499716.1335988412,
        "deployedUsd": 0,
        "markets": 1
      }
    ],
    "morphoProductiveUsd": 3735811.672794226,
    "morphoBorrowUsd": 3316653.292491593,
    "markets": [
      {
        "market": "PAXG/USDC",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 1230372967.8034806,
        "borrowUsd": 1230372967.8034806,
        "collateralUsd": 245.87673788842454,
        "util": 100,
        "ghost": true
      },
      {
        "market": "XAUt/USDT",
        "collateral": "XAUt",
        "chain": "Ethereum",
        "supplyUsd": 3105115.801063622,
        "borrowUsd": 2798141.8403427973,
        "collateralUsd": 7179415.4663163675,
        "util": 90.11392874250699,
        "ghost": false
      },
      {
        "market": "PAXG/PYUSD",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 327360.51331030886,
        "borrowUsd": 295197.88458841766,
        "collateralUsd": 528571.2488207716,
        "util": 90.17516547837158,
        "ghost": false
      },
      {
        "market": "XAUt0/USDC",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 180506.2023373088,
        "borrowUsd": 162122.0543992243,
        "collateralUsd": 296132.11482734414,
        "util": 89.81522645757603,
        "ghost": false
      },
      {
        "market": "XAUt0/USDT0",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 61814.718598289364,
        "borrowUsd": 38030.277347141346,
        "collateralUsd": 71383.34484577297,
        "util": 61.52301298059098,
        "ghost": false
      },
      {
        "market": "XAUt/tGBP",
        "collateral": "XAUt",
        "chain": "Ethereum",
        "supplyUsd": 18699.244371050456,
        "borrowUsd": 1.2555652101826427,
        "collateralUsd": 42015.83316750155,
        "util": 0.0067145237811131,
        "ghost": false
      },
      {
        "market": "PAXG/tGBP",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 15029.460420613681,
        "borrowUsd": 0.9158209074286302,
        "collateralUsd": 3.475479639853827,
        "util": 0.0060935049016965,
        "ghost": false
      },
      {
        "market": "XAUt0/USDT0",
        "collateral": "XAUt0",
        "chain": "Arbitrum One",
        "supplyUsd": 12937.667122932009,
        "borrowUsd": 10659.064516836748,
        "collateralUsd": 25022.460145237073,
        "util": 82.3878402153628,
        "ghost": false
      },
      {
        "market": "XAUt0/USDC",
        "collateral": "XAUt0",
        "chain": "Arbitrum One",
        "supplyUsd": 10109.27275425823,
        "borrowUsd": 9179.059613450081,
        "collateralUsd": 18533.22337056842,
        "util": 90.79841682561857,
        "ghost": false
      },
      {
        "market": "XAUt0/AUSD",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 4048.5487330782953,
        "borrowUsd": 3320.9402976075835,
        "collateralUsd": 7855.912699221254,
        "util": 82.0279195474207,
        "ghost": false
      },
      {
        "market": "rXAUt/USDC",
        "collateral": "rXAUt",
        "chain": "World Chain",
        "supplyUsd": 190.2440827641772,
        "borrowUsd": 0,
        "collateralUsd": 0,
        "util": 0,
        "ghost": false
      }
    ]
  },
  "leads": [
    {
      "name": "Gauntlet",
      "aumUsd": 698991420.98399,
      "verified": true,
      "rwaUsd": 15317908.500198798,
      "holds": [
        "AA_FalconXUSDC",
        "SPYon",
        "QQQon"
      ],
      "goldActive": false
    },
    {
      "name": "Steakhouse Financial",
      "aumUsd": 1047739796.3117322,
      "verified": true,
      "rwaUsd": 6664192.842890743,
      "holds": [
        "XAUt",
        "FLHYon",
        "mF-ONE",
        "USCC",
        "AA_FalconXUSDC",
        "deSPXA",
        "EUTBL",
        "XAUt0"
      ],
      "goldActive": true
    },
    {
      "name": "Hyperithm",
      "aumUsd": 3770606.4615250495,
      "verified": true,
      "rwaUsd": 2827810.04612296,
      "holds": [
        "mHyperBTC",
        "mHYPER"
      ],
      "goldActive": false
    },
    {
      "name": "MEV Capital",
      "aumUsd": 8955775.705791045,
      "verified": true,
      "rwaUsd": 1281514.466465858,
      "holds": [
        "mF-ONE",
        "mHYPER"
      ],
      "goldActive": false
    },
    {
      "name": "Felix",
      "aumUsd": 49940548.30815263,
      "verified": true,
      "rwaUsd": 416683.58641347155,
      "holds": [
        "thBILL"
      ],
      "goldActive": false
    },
    {
      "name": "Clearstar",
      "aumUsd": 10465772.173115103,
      "verified": true,
      "rwaUsd": 258177.96208044817,
      "holds": [
        "mF-ONE",
        "AA_FalconXUSDC",
        "mBASIS"
      ],
      "goldActive": false
    },
    {
      "name": "UltraYield",
      "aumUsd": 878487.3888462683,
      "verified": true,
      "rwaUsd": 12660.567979008132,
      "holds": [
        "mBASIS"
      ],
      "goldActive": false
    }
  ]
};
