// AUTO-GENERATED by goldfish_prep.mjs
window.GOLDFISH_DATA = {
  "meta": {
    "generated": "2026-06-11T10:00:00Z"
  },
  "ggbr": {
    "supply": 25000000,
    "backingUsd": 104211250,
    "price": 4.172,
    "marketCapUsd": 104301211,
    "ionAuCollateralOz": 25000,
    "defiTvlUsd": 6200000,
    "stakedUsd": 1300000,
    "source": "dune.com/goldfishgold_main/goldfishgold-protocol-analysis"
  },
  "activation": {
    "backingUsd": 104211250,
    "defiTvlUsd": 6200000,
    "dormantUsd": 98011250,
    "activatedPct": 5.949453633844715,
    "tokGoldTotalUsd": 4501570752,
    "ggbrSharePct": 2.3149974917910607
  },
  "demand": {
    "tokGold": {
      "XAUt": 2576802754,
      "PAXG": 1924767998,
      "goldOz": 4211.86
    },
    "tokGoldTotalUsd": 4501570752,
    "productiveDefiUsd": 3732438.3412443106,
    "productiveBorrowUsd": 3314624.3599134996,
    "idleUsd": 4497838313.658755,
    "categoryActivationPct": 0.08291413257441368,
    "avgUtilPct": 59.99793061894705,
    "markets": [
      {
        "market": "PAXG/USDC",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 1214694997.686442,
        "borrowUsd": 1214694997.686442,
        "collateralUsd": 246.09388786673455,
        "util": 100,
        "ghost": true
      },
      {
        "market": "XAUt/USDT",
        "collateral": "XAUt",
        "chain": "Ethereum",
        "supplyUsd": 3102024.1694913446,
        "borrowUsd": 2797730.6287094094,
        "collateralUsd": 7188931.150479871,
        "util": 90.19048453024038,
        "ghost": false
      },
      {
        "market": "PAXG/PYUSD",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 327279.77807007916,
        "borrowUsd": 295121.8257055056,
        "collateralUsd": 529038.0649832212,
        "util": 90.17417068839258,
        "ghost": false
      },
      {
        "market": "XAUt0/USDC",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 180666.0956735643,
        "borrowUsd": 162076.47882916653,
        "collateralUsd": 296076.16167344776,
        "util": 89.71051166236175,
        "ghost": false
      },
      {
        "market": "XAUt0/USDT0",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 61936.90482483093,
        "borrowUsd": 36531.261003672626,
        "collateralUsd": 68936.9525034504,
        "util": 58.98141198206436,
        "ghost": false
      },
      {
        "market": "XAUt/tGBP",
        "collateral": "XAUt",
        "chain": "Ethereum",
        "supplyUsd": 18713.243998749076,
        "borrowUsd": 1.2564950998399513,
        "collateralUsd": 42069.013347269574,
        "util": 0.0067144697088540005,
        "ghost": false
      },
      {
        "market": "PAXG/tGBP",
        "collateral": "PAXG",
        "chain": "Ethereum",
        "supplyUsd": 15040.712579327801,
        "borrowUsd": 0.9164992327002103,
        "collateralUsd": 3.4785490653508973,
        "util": 0.0060934561967486,
        "ghost": false
      },
      {
        "market": "XAUt0/USDT0",
        "collateral": "XAUt0",
        "chain": "Arbitrum One",
        "supplyUsd": 12938.16074297903,
        "borrowUsd": 10659.382721111566,
        "collateralUsd": 25017.732236667653,
        "util": 82.38715635756762,
        "ghost": false
      },
      {
        "market": "XAUt0/USDC",
        "collateral": "XAUt0",
        "chain": "Arbitrum One",
        "supplyUsd": 10187.354482237177,
        "borrowUsd": 9177.926914020438,
        "collateralUsd": 18529.72158117265,
        "util": 90.0913669984019,
        "ghost": false
      },
      {
        "market": "XAUt0/AUSD",
        "collateral": "XAUt0",
        "chain": "Monad",
        "supplyUsd": 3434.894840651188,
        "borrowUsd": 3320.8837760304964,
        "collateralUsd": 7854.42835128921,
        "util": 96.68079897901394,
        "ghost": false
      },
      {
        "market": "rXAUt/USDC",
        "collateral": "rXAUt",
        "chain": "World Chain",
        "supplyUsd": 217.02654054718303,
        "borrowUsd": 3.799260250223944,
        "collateralUsd": 0,
        "util": 1.7505970655224812,
        "ghost": false
      }
    ]
  },
  "leads": [
    {
      "name": "Gauntlet",
      "aumUsd": 698991420.98399,
      "verified": true,
      "rwaUsd": 15317908.500198798,
      "holds": [
        "AA_FalconXUSDC",
        "SPYon",
        "QQQon"
      ],
      "goldActive": false
    },
    {
      "name": "Steakhouse Financial",
      "aumUsd": 1047739796.3117322,
      "verified": true,
      "rwaUsd": 6664192.842890743,
      "holds": [
        "XAUt",
        "FLHYon",
        "mF-ONE",
        "USCC",
        "AA_FalconXUSDC",
        "deSPXA",
        "EUTBL",
        "XAUt0"
      ],
      "goldActive": true
    },
    {
      "name": "Hyperithm",
      "aumUsd": 3770606.4615250495,
      "verified": true,
      "rwaUsd": 2827810.04612296,
      "holds": [
        "mHyperBTC",
        "mHYPER"
      ],
      "goldActive": false
    },
    {
      "name": "MEV Capital",
      "aumUsd": 8955775.705791045,
      "verified": true,
      "rwaUsd": 1281514.466465858,
      "holds": [
        "mF-ONE",
        "mHYPER"
      ],
      "goldActive": false
    },
    {
      "name": "Felix",
      "aumUsd": 49940548.30815263,
      "verified": true,
      "rwaUsd": 416683.58641347155,
      "holds": [
        "thBILL"
      ],
      "goldActive": false
    },
    {
      "name": "Clearstar",
      "aumUsd": 10465772.173115103,
      "verified": true,
      "rwaUsd": 258177.96208044817,
      "holds": [
        "mF-ONE",
        "AA_FalconXUSDC",
        "mBASIS"
      ],
      "goldActive": false
    },
    {
      "name": "UltraYield",
      "aumUsd": 878487.3888462683,
      "verified": true,
      "rwaUsd": 12660.567979008132,
      "holds": [
        "mBASIS"
      ],
      "goldActive": false
    }
  ]
};
