// AUTO-GENERATED by build.mjs — do not edit by hand.
window.CURATOR_DATA = {
  "meta": {
    "generated": "2026-06-10T18:35:00Z",
    "totalAumUsd": 2243999551.4738903,
    "curatorCount": 27,
    "protocols": [
      "Morpho",
      "Euler"
    ],
    "note": "Curator AUM = capital allocated via curated vaults (Morpho MetaMorpho + Euler Earn). Aave entries are risk service providers (advisory), excluded from AUM totals."
  },
  "curators": [
    {
      "name": "Steakhouse Financial",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 1047739796.3117322,
      "vaultCount": 29,
      "byChain": {
        "Base": 620563802.626641,
        "Ethereum": 396876396.7082238,
        "Katana": 24913973.927930605,
        "Monad": 2539079.6353452513,
        "Arbitrum One": 2563934.6320567373,
        "Polygon": 282608.78153469815
      },
      "byAssetType": {
        "ETH / LST / LRT": 169478051.85198507,
        "BTC": 726566093.2462698,
        "Stablecoin": 128375224.34965464,
        "RWA / Credit": 6671396.462636671,
        "Pendle / Fixed-term": 12999414.561907455,
        "Altcoin / L1": 3492565.1388444225
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 1047739796.3117322,
          "vaultCount": 29
        }
      ],
      "chains": [
        "Base",
        "Ethereum",
        "Katana",
        "Monad",
        "Arbitrum One",
        "Polygon"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 69%, ETH / LST / LRT 16%, Stablecoin 12%, Pendle / Fixed-term 1%, RWA / Credit 1%, Altcoin / L1 0%",
      "ethShare": 0.37879290078062655,
      "sizeTier": "Mega (>$500M)"
    },
    {
      "name": "Gauntlet",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 698991420.98399,
      "vaultCount": 43,
      "byChain": {
        "Base": 451370730.4296647,
        "Ethereum": 214303533.66125908,
        "Katana": 17922933.08233222,
        "OP Mainnet": 4210379.09340128,
        "Arbitrum One": 4233851.1598206945,
        "Polygon": 4366053.805732826,
        "HyperEVM": 2583939.7517789607
      },
      "byAssetType": {
        "ETH / LST / LRT": 117442143.48230751,
        "BTC": 530709064.485454,
        "Stablecoin": 28073273.489821173,
        "RWA / Credit": 15333118.562754173,
        "Pendle / Fixed-term": 3278604.8720886074,
        "Altcoin / L1": 4155216.0915644574
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 698991420.98399,
          "vaultCount": 43
        }
      ],
      "chains": [
        "Base",
        "Ethereum",
        "Katana",
        "OP Mainnet",
        "Arbitrum One",
        "Polygon",
        "HyperEVM"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 76%, ETH / LST / LRT 17%, Stablecoin 4%, RWA / Credit 2%, Altcoin / L1 1%, Pendle / Fixed-term 0%",
      "ethShare": 0.30658964792383,
      "sizeTier": "Mega (>$500M)"
    },
    {
      "name": "Sentora",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 289875914.2733289,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 289875914.2733289
      },
      "byAssetType": {
        "BTC": 119026510.86994055,
        "ETH / LST / LRT": 52163966.63344777,
        "Pendle / Fixed-term": 25.18933394474774,
        "Stablecoin": 42506363.659500524,
        "RWA / Credit": 76179047.92110616
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 289875914.2733289,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 41%, RWA / Credit 26%, ETH / LST / LRT 18%, Stablecoin 15%, Pendle / Fixed-term 0%",
      "ethShare": 1,
      "sizeTier": "Large ($100M–500M)"
    },
    {
      "name": "Felix",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 49940548.30815263,
      "vaultCount": 7,
      "byChain": {
        "HyperEVM": 49940548.30815263
      },
      "byAssetType": {
        "Pendle / Fixed-term": 38905.80492664557,
        "Altcoin / L1": 47948684.34269448,
        "BTC": 1273377.1977064789,
        "RWA / Credit": 416683.58641347155,
        "Stablecoin": 170579.35512284434,
        "ETH / LST / LRT": 92318.02128871022
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 49940548.30815263,
          "vaultCount": 7
        }
      ],
      "chains": [
        "HyperEVM"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Altcoin / L1",
      "assetProfile": "Altcoin / L1 96%, BTC 3%, RWA / Credit 1%, Stablecoin 0%, ETH / LST / LRT 0%, Pendle / Fixed-term 0%",
      "ethShare": 0,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Yearn",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 31347193.306066252,
      "vaultCount": 11,
      "byChain": {
        "Katana": 17881222.935128685,
        "Ethereum": 11233325.428761842,
        "Base": 2200426.6470497944,
        "Arbitrum One": 32218.295125932724
      },
      "byAssetType": {
        "ETH / LST / LRT": 17483734.311148413,
        "BTC": 6125379.379212617,
        "Altcoin / L1": 2083476.7243333342,
        "Stablecoin": 5445701.416666401,
        "Pendle / Fixed-term": 176683.17957955477,
        "RWA / Credit": 32218.295125932724
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 31347193.306066252,
          "vaultCount": 11
        }
      ],
      "chains": [
        "Katana",
        "Ethereum",
        "Base",
        "Arbitrum One"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 56%, BTC 20%, Stablecoin 17%, Altcoin / L1 7%, Pendle / Fixed-term 1%, RWA / Credit 0%",
      "ethShare": 0.35835187281624953,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Pangolins",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 27927592.14911528,
      "vaultCount": 1,
      "byChain": {
        "Base": 27927592.14911528
      },
      "byAssetType": {
        "BTC": 27927592.14911528
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 27927592.14911528,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 100%",
      "ethShare": 0,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Hakutora",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 27603921.48010356,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 27603921.48010356
      },
      "byAssetType": {
        "BTC": 20071404.32459834,
        "ETH / LST / LRT": 7532517.155505225
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 27603921.48010356,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 73%, ETH / LST / LRT 27%",
      "ethShare": 1,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Anthias Labs",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 18618975.18865401,
      "vaultCount": 5,
      "byChain": {
        "Base": 18618975.18865401
      },
      "byAssetType": {
        "BTC": 7455917.935130857,
        "ETH / LST / LRT": 11060571.013316307,
        "Stablecoin": 27590.212068012384,
        "Altcoin / L1": 74896.02813883527
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 18618975.18865401,
          "vaultCount": 5
        }
      ],
      "chains": [
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 59%, BTC 40%, Altcoin / L1 0%, Stablecoin 0%",
      "ethShare": 0,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "Clearstar",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 10471204.264623605,
      "vaultCount": 6,
      "byChain": {
        "Ethereum": 7082262.26256346,
        "Base": 3328643.414131074,
        "Arbitrum One": 60298.587929069545
      },
      "byAssetType": {
        "Stablecoin": 7314169.995307124,
        "RWA / Credit": 258177.96208044817,
        "BTC": 1571869.6309173189,
        "ETH / LST / LRT": 803295.9095691838,
        "Altcoin / L1": 523690.7667495302
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 10465772.173115103,
          "vaultCount": 5
        },
        {
          "protocol": "Euler",
          "aumUsd": 5432.091508501699,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum",
        "Base",
        "Arbitrum One"
      ],
      "protocol": "Morpho + Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 70%, BTC 15%, ETH / LST / LRT 8%, Altcoin / L1 5%, RWA / Credit 2%",
      "ethShare": 0.6763560411566507,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "MEV Capital",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 8955775.705791045,
      "vaultCount": 5,
      "byChain": {
        "Ethereum": 8192868.971697674,
        "HyperEVM": 762906.7340933713
      },
      "byAssetType": {
        "Stablecoin": 2511271.8568531107,
        "ETH / LST / LRT": 3913790.09330235,
        "BTC": 429606.91316402727,
        "RWA / Credit": 1281514.466465858,
        "Altcoin / L1": 762906.7340933713,
        "Pendle / Fixed-term": 56685.64191232773
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 8955775.705791045,
          "vaultCount": 5
        }
      ],
      "chains": [
        "Ethereum",
        "HyperEVM"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 44%, Stablecoin 28%, RWA / Credit 14%, Altcoin / L1 9%, BTC 5%, Pendle / Fixed-term 1%",
      "ethShare": 0.9148139972286203,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "SparkDAO",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 8733919.310007378,
      "vaultCount": 2,
      "byChain": {
        "Base": 7734097.691395241,
        "Ethereum": 999821.618612138
      },
      "byAssetType": {
        "BTC": 500792.21330831386,
        "ETH / LST / LRT": 8233127.096699065
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 8733919.310007378,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Base",
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 94%, BTC 6%",
      "ethShare": 0.1144757105171027,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "TelosC",
      "relationshipType": "curator",
      "verified": false,
      "aumUsd": 5751648.669006471,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 5751648.669006471
      },
      "byAssetType": {
        "BTC": 3465562.9762650253,
        "ETH / LST / LRT": 2286085.6927414457
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 5751648.669006471,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 60%, ETH / LST / LRT 40%",
      "ethShare": 1,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "Euler (native)",
      "relationshipType": "curator",
      "verified": false,
      "aumUsd": 4007666.0291506876,
      "vaultCount": 6,
      "byChain": {
        "Ethereum": 3442920.60301803,
        "Arbitrum": 560012.5612603555,
        "Base": 4732.864872302134
      },
      "byAssetType": {
        "Stablecoin": 3968737.56832358,
        "ETH / LST / LRT": 38928.460827107345
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 4007666.0291506876,
          "vaultCount": 6
        }
      ],
      "chains": [
        "Ethereum",
        "Arbitrum",
        "Base"
      ],
      "protocol": "Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 99%, ETH / LST / LRT 1%",
      "ethShare": 0.8590837105624942,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Hyperithm",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 3781573.406156063,
      "vaultCount": 6,
      "byChain": {
        "Ethereum": 3019181.844686015,
        "Arbitrum One": 702896.6887804727,
        "HyperEVM": 59494.872689575226
      },
      "byAssetType": {
        "ETH / LST / LRT": 354598.7672700731,
        "RWA / Credit": 2829817.559530583,
        "Pendle / Fixed-term": 255346.51901975163,
        "BTC": 213019.38217145554,
        "Stablecoin": 69296.30547462427,
        "Altcoin / L1": 59494.87268957522
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 3770606.4615250495,
          "vaultCount": 5
        },
        {
          "protocol": "Euler",
          "aumUsd": 10966.94463101363,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum",
        "Arbitrum One",
        "HyperEVM"
      ],
      "protocol": "Morpho + Euler",
      "dominantAssetType": "RWA / Credit",
      "assetProfile": "RWA / Credit 75%, ETH / LST / LRT 9%, Pendle / Fixed-term 7%, BTC 6%, Stablecoin 2%, Altcoin / L1 2%",
      "ethShare": 0.7983930286190022,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "AlphaPing",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 3198176.5939038727,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 3198176.5939038727
      },
      "byAssetType": {
        "Stablecoin": 2046504.5013759069,
        "ETH / LST / LRT": 1151672.0925279658
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 3198176.5939038727,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 64%, ETH / LST / LRT 36%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Cassa RWAs",
      "relationshipType": "curator",
      "verified": false,
      "aumUsd": 1607897.8616198653,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 1607897.8616198653
      },
      "byAssetType": {
        "RWA / Credit": 1607897.8616198653
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 1607897.8616198653,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "RWA / Credit",
      "assetProfile": "RWA / Credit 100%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "RE7 Labs",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 1244938.563451907,
      "vaultCount": 7,
      "byChain": {
        "Ethereum": 835429.3539586698,
        "Base": 409509.20949323697
      },
      "byAssetType": {
        "ETH / LST / LRT": 741740.527135271,
        "BTC": 253550.68821606424,
        "Stablecoin": 22340.77597072328
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 1244938.563451907,
          "vaultCount": 7
        }
      ],
      "chains": [
        "Ethereum",
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 73%, BTC 25%, Stablecoin 2%",
      "ethShare": 0.671060708122199,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "kpk RWA",
      "relationshipType": "curator",
      "verified": false,
      "aumUsd": 1012374.5399898747,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 1012374.5399898747
      },
      "byAssetType": {
        "Stablecoin": 1012374.5399898747
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 1012374.5399898747,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 100%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "SingularV",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 977840.676715851,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 977840.676715851
      },
      "byAssetType": {
        "ETH / LST / LRT": 943921.520472699,
        "BTC": 1245.6341142061874,
        "Stablecoin": 32673.522128945642
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 977840.676715851,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 97%, Stablecoin 3%, BTC 0%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "UltraYield",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 878487.3888462683,
      "vaultCount": 4,
      "byChain": {
        "Base": 643281.0715802223,
        "Arbitrum One": 102175.906769487,
        "OP Mainnet": 102002.8229895628,
        "Ethereum": 31027.587506996224
      },
      "byAssetType": {
        "BTC": 701511.4606047566,
        "ETH / LST / LRT": 115918.47162504954,
        "RWA / Credit": 12660.567979008132,
        "Stablecoin": 48396.888637454
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 878487.3888462683,
          "vaultCount": 4
        }
      ],
      "chains": [
        "Base",
        "Arbitrum One",
        "OP Mainnet",
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 80%, ETH / LST / LRT 13%, Stablecoin 6%, RWA / Credit 1%",
      "ethShare": 0.03531933172967373,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Infinifi USDC",
      "relationshipType": "curator",
      "verified": false,
      "aumUsd": 380682.9230826275,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 380682.9230826275
      },
      "byAssetType": {
        "Stablecoin": 380682.9230826275
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 380682.9230826275,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 100%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Apostro",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 264250.25370197,
      "vaultCount": 1,
      "byChain": {
        "Base": 264250.25370197
      },
      "byAssetType": {
        "ETH / LST / LRT": 249692.42896138513,
        "BTC": 14557.824740584827
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 264250.25370197,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 94%, BTC 6%",
      "ethShare": 0,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "B.Protocol",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 253460.67779461082,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 253460.67779461082
      },
      "byAssetType": {},
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 253460.67779461082,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Other / Long-tail",
      "assetProfile": "",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Block Analitica",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 253460.67779461082,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 253460.67779461082
      },
      "byAssetType": {},
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 253460.67779461082,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Other / Long-tail",
      "assetProfile": "",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Keyrock",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 95939.81752281035,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 95939.81752281035
      },
      "byAssetType": {},
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 95939.81752281035,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Other / Long-tail",
      "assetProfile": "",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "TiD Capital",
      "relationshipType": "curator",
      "verified": false,
      "aumUsd": 59895.9451482096,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 59895.9451482096
      },
      "byAssetType": {
        "ETH / LST / LRT": 32809.936609247874,
        "Stablecoin": 27086.008538961723
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 59895.9451482096,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 55%, Stablecoin 45%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "K3 Capital",
      "relationshipType": "curator",
      "verified": true,
      "aumUsd": 24996.168439871493,
      "vaultCount": 1,
      "byChain": {
        "Unichain": 24996.168439871493
      },
      "byAssetType": {
        "ETH / LST / LRT": 24996.168439871493
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 24996.168439871493,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Unichain"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 100%",
      "ethShare": 0,
      "sizeTier": "Emerging (<$5M)"
    }
  ],
  "riskManagers": [
    {
      "name": "Gauntlet",
      "protocol": "Aave",
      "relationshipType": "risk_manager",
      "verified": true,
      "aumUsd": 0,
      "overseesUsd": 11509605625.305305,
      "scope": "Risk params, caps, IR curves across Aave v3 markets",
      "byAssetType": {},
      "byChain": {},
      "chains": [],
      "dominantAssetType": "—",
      "assetProfile": "advisory — not capital allocation"
    },
    {
      "name": "Chaos Labs",
      "protocol": "Aave",
      "relationshipType": "risk_manager",
      "verified": true,
      "aumUsd": 0,
      "overseesUsd": 11509605625.305305,
      "scope": "Risk params, oracle & listing risk across Aave v3 markets",
      "byAssetType": {},
      "byChain": {},
      "chains": [],
      "dominantAssetType": "—",
      "assetProfile": "advisory — not capital allocation"
    }
  ],
  "agg": {
    "byAssetType": {
      "ETH / LST / LRT": 394143879.6351798,
      "BTC": 1446307056.3109295,
      "Stablecoin": 222032267.36851653,
      "RWA / Credit": 104622533.24571218,
      "Pendle / Fixed-term": 16805665.76876829,
      "Altcoin / L1": 59100930.699108005
    },
    "byChain": {
      "Base": 1133066041.5462987,
      "Ethereum": 977087982.176299,
      "Katana": 60718129.945391506,
      "Monad": 2539079.6353452513,
      "Arbitrum One": 7695375.270482394,
      "Polygon": 4648662.587267524,
      "OP Mainnet": 4312381.916390843,
      "HyperEVM": 53346889.666714534,
      "Arbitrum": 560012.5612603555,
      "Unichain": 24996.168439871493
    },
    "byProtocol": {
      "Morpho": 2231162986.4697533,
      "Euler": 12836565.004137252
    },
    "byTier": {
      "Mega (>$500M)": 1746731217.295722,
      "Large ($100M–500M)": 289875914.2733289,
      "Mid ($25M–100M)": 136819255.24343774,
      "Small ($5M–25M)": 52531523.138082504,
      "Emerging (<$5M)": 18041641.5233191
    }
  },
  "assetColors": {
    "BTC": "var(--orange)",
    "ETH / LST / LRT": "var(--blue)",
    "Stablecoin": "var(--green)",
    "RWA / Credit": "var(--purple)",
    "Pendle / Fixed-term": "var(--yellow)",
    "Altcoin / L1": "var(--red)",
    "Other / Long-tail": "var(--fg-muted)"
  }
};
