// AUTO-GENERATED by build.mjs, do not edit by hand.
window.CURATOR_DATA = {
  "meta": {
    "generated": "2026-06-11T19:00:00Z",
    "totalAumUsd": 2145511938.637087,
    "curatorCount": 27,
    "protocols": [
      "Morpho",
      "Euler"
    ],
    "note": "Curator AUM = capital allocated via curated vaults (Morpho MetaMorpho + Euler Earn). Aave entries are risk service providers (advisory), excluded from AUM totals."
  },
  "curators": [
    {
      "name": "Steakhouse Financial",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x043a816DcE5478eff35d665f985dc4540E9fFD03",
      "aumUsd": 944556270.1364113,
      "vaultCount": 29,
      "byChain": {
        "Base": 532416673.7435155,
        "Ethereum": 382269055.9483476,
        "Katana": 24799440.721860986,
        "Arbitrum One": 2742404.8146099886,
        "Monad": 1982942.6537386514,
        "Polygon": 345752.2543386101
      },
      "byAssetType": {
        "BTC": 637913150.5653912,
        "ETH / LST / LRT": 163086619.58326396,
        "Stablecoin": 123126953.90704817,
        "RWA / Credit": 5840321.785128386,
        "Pendle / Fixed-term": 13123804.775588691,
        "Altcoin / L1": 1308358.7939289706
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 944556270.1364113,
          "vaultCount": 29
        }
      ],
      "chains": [
        "Base",
        "Ethereum",
        "Katana",
        "Arbitrum One",
        "Monad",
        "Polygon"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 68%, ETH / LST / LRT 17%, Stablecoin 13%, Pendle / Fixed-term 1%, RWA / Credit 1%, Altcoin / L1 0%",
      "ethShare": 0.4047075521431253,
      "sizeTier": "Mega (>$500M)"
    },
    {
      "name": "Gauntlet",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x9E33faAE38ff641094fa68c65c2cE600b3410585",
      "aumUsd": 663263313.3188086,
      "vaultCount": 43,
      "byChain": {
        "Base": 423648120.4168363,
        "Ethereum": 207624732.51324692,
        "Katana": 19251393.805549357,
        "OP Mainnet": 4066896.9692014977,
        "Arbitrum One": 4238831.214707075,
        "HyperEVM": 2799679.819663296,
        "Polygon": 1633658.5796039877
      },
      "byAssetType": {
        "BTC": 503005578.62278545,
        "ETH / LST / LRT": 114141191.86238027,
        "Stablecoin": 25245984.127592083,
        "RWA / Credit": 15309278.99858106,
        "Pendle / Fixed-term": 2867166.270273598,
        "Altcoin / L1": 2694113.4371960172
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 663263313.3188086,
          "vaultCount": 43
        }
      ],
      "chains": [
        "Base",
        "Ethereum",
        "Katana",
        "OP Mainnet",
        "Arbitrum One",
        "HyperEVM",
        "Polygon"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 76%, ETH / LST / LRT 17%, Stablecoin 4%, RWA / Credit 2%, Pendle / Fixed-term 0%, Altcoin / L1 0%",
      "ethShare": 0.3130351526218798,
      "sizeTier": "Mega (>$500M)"
    },
    {
      "name": "Sentora",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x9e396dE3312D373b87F9BD8763fb48184b42aac0",
      "aumUsd": 292880433.5397914,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 292880433.5397914
      },
      "byAssetType": {
        "BTC": 122303675.08895226,
        "Stablecoin": 42232672.61108154,
        "RWA / Credit": 75878918.16125457,
        "ETH / LST / LRT": 52465142.16702593,
        "Pendle / Fixed-term": 25.511477108536234
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 292880433.5397914,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 42%, RWA / Credit 26%, ETH / LST / LRT 18%, Stablecoin 14%, Pendle / Fixed-term 0%",
      "ethShare": 1,
      "sizeTier": "Large ($100M–500M)"
    },
    {
      "name": "Felix",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x18e4961454B3E487B3f47c70b703684D894Ff979",
      "aumUsd": 67245426.67604329,
      "vaultCount": 7,
      "byChain": {
        "HyperEVM": 67245426.67604329
      },
      "byAssetType": {
        "Pendle / Fixed-term": 607926.084692636,
        "Altcoin / L1": 64686340.30925831,
        "BTC": 1290359.2662116608,
        "RWA / Credit": 408416.82759412396,
        "Stablecoin": 167344.63754693457,
        "ETH / LST / LRT": 85039.55073960587
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 67245426.67604329,
          "vaultCount": 7
        }
      ],
      "chains": [
        "HyperEVM"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Altcoin / L1",
      "assetProfile": "Altcoin / L1 96%, BTC 2%, Pendle / Fixed-term 1%, RWA / Credit 1%, Stablecoin 0%, ETH / LST / LRT 0%",
      "ethShare": 0,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Yearn",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x90D0f26025571295D18a6c041E47450B81886B51",
      "aumUsd": 31349040.325524468,
      "vaultCount": 11,
      "byChain": {
        "Katana": 18625532.639902964,
        "Ethereum": 10526556.988382874,
        "Base": 2164729.4685684764,
        "Arbitrum One": 32221.228670158373
      },
      "byAssetType": {
        "ETH / LST / LRT": 16896497.517358005,
        "BTC": 6980147.133411915,
        "Altcoin / L1": 2166084.625461591,
        "Stablecoin": 5222072.95369522,
        "Pendle / Fixed-term": 52016.866927580806,
        "RWA / Credit": 32221.228670158373
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 31349040.325524468,
          "vaultCount": 11
        }
      ],
      "chains": [
        "Katana",
        "Ethereum",
        "Base",
        "Arbitrum One"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 54%, BTC 22%, Stablecoin 17%, Altcoin / L1 7%, Pendle / Fixed-term 0%, RWA / Credit 0%",
      "ethShare": 0.33578562147601454,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Pangolins",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x9855475778aa3B492C14E4E12ca0d44c253C9884",
      "aumUsd": 30720911.063117485,
      "vaultCount": 1,
      "byChain": {
        "Base": 30720911.063117485
      },
      "byAssetType": {
        "BTC": 30720911.063117485
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 30720911.063117485,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 100%",
      "ethShare": 0,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Hakutora",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x2413A57FBD695f6B13C1D8d7D30EE10fa61b1b02",
      "aumUsd": 27354849.269517332,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 27354849.269517332
      },
      "byAssetType": {
        "BTC": 19769314.596152276,
        "ETH / LST / LRT": 7585534.673365058
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 27354849.269517332,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 72%, ETH / LST / LRT 28%",
      "ethShare": 1,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "SparkDAO",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x0f963A8A8c01042B69054e787E5763ABbB0646A3",
      "aumUsd": 26291245.098949537,
      "vaultCount": 2,
      "byChain": {
        "Base": 19882257.657720245,
        "Ethereum": 6408987.441229292
      },
      "byAssetType": {
        "BTC": 16453333.900060156,
        "ETH / LST / LRT": 9837911.19888938
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 26291245.098949537,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Base",
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 63%, ETH / LST / LRT 37%",
      "ethShare": 0.24376888264928018,
      "sizeTier": "Mid ($25M–100M)"
    },
    {
      "name": "Anthias Labs",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x08eDEbFFaE68970DCf751baa826182b3a4aCFC05",
      "aumUsd": 19136774.283202138,
      "vaultCount": 5,
      "byChain": {
        "Base": 19136774.283202138
      },
      "byAssetType": {
        "ETH / LST / LRT": 11050483.863958443,
        "BTC": 7982003.096997297,
        "Stablecoin": 27826.486152086647,
        "Altcoin / L1": 76460.83609431083
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 19136774.283202138,
          "vaultCount": 5
        }
      ],
      "chains": [
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 58%, BTC 42%, Altcoin / L1 0%, Stablecoin 0%",
      "ethShare": 0,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "Clearstar",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x30988479C2E6a03E7fB65138b94762D41a733458",
      "aumUsd": 10077984.791161714,
      "vaultCount": 6,
      "byChain": {
        "Ethereum": 6706822.599813832,
        "Base": 3312106.8939650203,
        "Arbitrum One": 59055.29738285873
      },
      "byAssetType": {
        "Stablecoin": 7026155.355590103,
        "BTC": 1680487.8500649387,
        "ETH / LST / LRT": 850804.5507989596,
        "Altcoin / L1": 520537.0347077107
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 10072552.699653212,
          "vaultCount": 5
        },
        {
          "protocol": "Euler",
          "aumUsd": 5432.091508501699,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum",
        "Base",
        "Arbitrum One"
      ],
      "protocol": "Morpho + Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 70%, BTC 17%, ETH / LST / LRT 8%, Altcoin / L1 5%",
      "ethShare": 0.6654924311550504,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "MEV Capital",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x06590Fef209Ebc1f8eEF83dA05984cD4eFf0d0E3",
      "aumUsd": 9080105.52730931,
      "vaultCount": 5,
      "byChain": {
        "Ethereum": 8202576.371549144,
        "HyperEVM": 877529.1557601676
      },
      "byAssetType": {
        "Stablecoin": 2325908.4339019423,
        "RWA / Credit": 926398.8684304255,
        "ETH / LST / LRT": 4472202.048494674,
        "BTC": 385377.88376568875,
        "Altcoin / L1": 877529.1557601676,
        "Pendle / Fixed-term": 92689.13695641315
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 9080105.52730931,
          "vaultCount": 5
        }
      ],
      "chains": [
        "Ethereum",
        "HyperEVM"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 49%, Stablecoin 26%, RWA / Credit 10%, Altcoin / L1 10%, BTC 4%, Pendle / Fixed-term 1%",
      "ethShare": 0.9033569430310132,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "TelosC",
      "relationshipType": "curator",
      "morphoListed": false,
      "address": null,
      "aumUsd": 5751648.669006471,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 5751648.669006471
      },
      "byAssetType": {
        "BTC": 3465562.9762650253,
        "ETH / LST / LRT": 2286085.6927414457
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 5751648.669006471,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 60%, ETH / LST / LRT 40%",
      "ethShare": 1,
      "sizeTier": "Small ($5M–25M)"
    },
    {
      "name": "Euler (native)",
      "relationshipType": "curator",
      "morphoListed": false,
      "address": null,
      "aumUsd": 4007666.0291506876,
      "vaultCount": 6,
      "byChain": {
        "Ethereum": 3442920.60301803,
        "Arbitrum": 560012.5612603555,
        "Base": 4732.864872302134
      },
      "byAssetType": {
        "Stablecoin": 3968737.56832358,
        "ETH / LST / LRT": 38928.460827107345
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 4007666.0291506876,
          "vaultCount": 6
        }
      ],
      "chains": [
        "Ethereum",
        "Arbitrum",
        "Base"
      ],
      "protocol": "Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 99%, ETH / LST / LRT 1%",
      "ethShare": 0.8590837105624942,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Hyperithm",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x75178137D3B4B9A0F771E0e149b00fB8167BA325",
      "aumUsd": 3720745.749490101,
      "vaultCount": 6,
      "byChain": {
        "Ethereum": 3026860.6216137907,
        "Arbitrum One": 634360.712492871,
        "HyperEVM": 59524.415383438885
      },
      "byAssetType": {
        "RWA / Credit": 2889865.0490285703,
        "ETH / LST / LRT": 398771.64311801654,
        "Pendle / Fixed-term": 185274.08638014813,
        "BTC": 123031.65282406837,
        "Stablecoin": 64278.902755859395,
        "Altcoin / L1": 59524.41538343888
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 3709778.8048590873,
          "vaultCount": 5
        },
        {
          "protocol": "Euler",
          "aumUsd": 10966.94463101363,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum",
        "Arbitrum One",
        "HyperEVM"
      ],
      "protocol": "Morpho + Euler",
      "dominantAssetType": "RWA / Credit",
      "assetProfile": "RWA / Credit 78%, ETH / LST / LRT 11%, Pendle / Fixed-term 5%, BTC 3%, Stablecoin 2%, Altcoin / L1 2%",
      "ethShare": 0.8135091256984164,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "AlphaPing",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x6788c8ad65E85CCa7224a0B46D061EF7D81F9Da5",
      "aumUsd": 3019634.349907179,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 3019634.349907179
      },
      "byAssetType": {
        "Stablecoin": 1834155.2017952392,
        "ETH / LST / LRT": 1185479.1481119397
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 3019634.349907179,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 61%, ETH / LST / LRT 39%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Cassa RWAs",
      "relationshipType": "curator",
      "morphoListed": false,
      "address": null,
      "aumUsd": 1607897.8616198653,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 1607897.8616198653
      },
      "byAssetType": {
        "RWA / Credit": 1607897.8616198653
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 1607897.8616198653,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "RWA / Credit",
      "assetProfile": "RWA / Credit 100%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "RE7 Labs",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0xE86399fE6d7007FdEcb08A2ee1434Ee677a04433",
      "aumUsd": 1250516.2195213735,
      "vaultCount": 7,
      "byChain": {
        "Ethereum": 840054.9640492902,
        "Base": 410461.2554720834
      },
      "byAssetType": {
        "ETH / LST / LRT": 747820.8331576225,
        "BTC": 253825.49445496977,
        "Stablecoin": 22345.61682631892
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 1250516.2195213735,
          "vaultCount": 7
        }
      ],
      "chains": [
        "Ethereum",
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 73%, BTC 25%, Stablecoin 2%",
      "ethShare": 0.6717665480347111,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "kpk RWA",
      "relationshipType": "curator",
      "morphoListed": false,
      "address": null,
      "aumUsd": 1012374.5399898747,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 1012374.5399898747
      },
      "byAssetType": {
        "Stablecoin": 1012374.5399898747
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 1012374.5399898747,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 100%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "SingularV",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x46057881E0B9d190920FB823F840B837f65745d5",
      "aumUsd": 976344.6766016665,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 976344.6766016665
      },
      "byAssetType": {
        "ETH / LST / LRT": 942394.4781031345,
        "BTC": 1262.8049074670637,
        "Stablecoin": 32687.393591065018
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 976344.6766016665,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 97%, Stablecoin 3%, BTC 0%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "UltraYield",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x1280e86Cd7787FfA55d37759C0342F8CD3c7594a",
      "aumUsd": 878778.432294301,
      "vaultCount": 4,
      "byChain": {
        "Base": 643498.613954931,
        "Arbitrum One": 102206.02160160882,
        "OP Mainnet": 102033.03659613318,
        "Ethereum": 31040.760141627965
      },
      "byAssetType": {
        "BTC": 701733.3722597051,
        "ETH / LST / LRT": 115958.55310506037,
        "RWA / Credit": 12672.612890231281,
        "Stablecoin": 48413.89403930423
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 878778.432294301,
          "vaultCount": 4
        }
      ],
      "chains": [
        "Base",
        "Arbitrum One",
        "OP Mainnet",
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "BTC",
      "assetProfile": "BTC 80%, ETH / LST / LRT 13%, Stablecoin 6%, RWA / Credit 1%",
      "ethShare": 0.0353226239981644,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Infinifi USDC",
      "relationshipType": "curator",
      "morphoListed": false,
      "address": null,
      "aumUsd": 380682.9230826275,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 380682.9230826275
      },
      "byAssetType": {
        "Stablecoin": 380682.9230826275
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 380682.9230826275,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "Stablecoin",
      "assetProfile": "Stablecoin 100%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Apostro",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0xC91578e51BCE35844E345CC7F733b4bBf6721734",
      "aumUsd": 263951.23240914964,
      "vaultCount": 1,
      "byChain": {
        "Base": 263951.23240914964
      },
      "byAssetType": {
        "ETH / LST / LRT": 249409.8914416565,
        "BTC": 14541.340967493128
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 263951.23240914964,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Base"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 94%, BTC 6%",
      "ethShare": 0,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "B.Protocol",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x2566f66f68ed438726AD904524FB306A03FdB80B",
      "aumUsd": 253502.7826462095,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 253502.7826462095
      },
      "byAssetType": {},
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 253502.7826462095,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Other / Long-tail",
      "assetProfile": "",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Block Analitica",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x2566f66f68ed438726AD904524FB306A03FdB80B",
      "aumUsd": 253502.7826462095,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 253502.7826462095
      },
      "byAssetType": {},
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 253502.7826462095,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Other / Long-tail",
      "assetProfile": "",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "Keyrock",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0x9ea3709E1A3f0B9501DD4a66163861D9BcCe7A08",
      "aumUsd": 95944.38640724425,
      "vaultCount": 1,
      "byChain": {
        "Ethereum": 95944.38640724425
      },
      "byAssetType": {},
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 95944.38640724425,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "Other / Long-tail",
      "assetProfile": "",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "TiD Capital",
      "relationshipType": "curator",
      "morphoListed": false,
      "address": null,
      "aumUsd": 59895.9451482096,
      "vaultCount": 2,
      "byChain": {
        "Ethereum": 59895.9451482096
      },
      "byAssetType": {
        "ETH / LST / LRT": 32809.936609247874,
        "Stablecoin": 27086.008538961723
      },
      "protocols": [
        {
          "protocol": "Euler",
          "aumUsd": 59895.9451482096,
          "vaultCount": 2
        }
      ],
      "chains": [
        "Ethereum"
      ],
      "protocol": "Euler",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 55%, Stablecoin 45%",
      "ethShare": 1,
      "sizeTier": "Emerging (<$5M)"
    },
    {
      "name": "K3 Capital",
      "relationshipType": "curator",
      "morphoListed": true,
      "address": "0xdD84A24eeddE63F10Ec3e928f1c8302A47538b6B",
      "aumUsd": 22498.027329116572,
      "vaultCount": 1,
      "byChain": {
        "Unichain": 22498.027329116572
      },
      "byAssetType": {
        "ETH / LST / LRT": 22498.027329116572
      },
      "protocols": [
        {
          "protocol": "Morpho",
          "aumUsd": 22498.027329116572,
          "vaultCount": 1
        }
      ],
      "chains": [
        "Unichain"
      ],
      "protocol": "Morpho",
      "dominantAssetType": "ETH / LST / LRT",
      "assetProfile": "ETH / LST / LRT 100%",
      "ethShare": 0,
      "sizeTier": "Emerging (<$5M)"
    }
  ],
  "riskManagers": [
    {
      "name": "Gauntlet",
      "protocol": "Aave",
      "relationshipType": "risk_manager",
      "morphoListed": false,
      "address": null,
      "aumUsd": 0,
      "overseesUsd": 11823974193.683632,
      "scope": "Risk params, caps, IR curves across Aave v3 markets",
      "govSource": "https://governance.aave.com",
      "byAssetType": {},
      "byChain": {},
      "chains": [],
      "dominantAssetType": "-",
      "assetProfile": "advisory, not capital allocation"
    },
    {
      "name": "Chaos Labs",
      "protocol": "Aave",
      "relationshipType": "risk_manager",
      "morphoListed": false,
      "address": null,
      "aumUsd": 0,
      "overseesUsd": 11823974193.683632,
      "scope": "Risk params, oracle & listing risk across Aave v3 markets",
      "govSource": "https://governance.aave.com",
      "byAssetType": {},
      "byChain": {},
      "chains": [],
      "dominantAssetType": "-",
      "assetProfile": "advisory, not capital allocation"
    }
  ],
  "agg": {
    "byAssetType": {
      "BTC": 1353044296.708589,
      "ETH / LST / LRT": 386491583.6808186,
      "Stablecoin": 212765680.56155092,
      "RWA / Credit": 102905991.3931974,
      "Pendle / Fixed-term": 16928902.732296176,
      "Altcoin / L1": 72388948.60779051
    },
    "byChain": {
      "Base": 1032604217.4936335,
      "Ethereum": 962726320.5377564,
      "Katana": 62676367.16731331,
      "Arbitrum One": 7809079.28946456,
      "Monad": 1982942.6537386514,
      "Polygon": 1979410.8339425977,
      "OP Mainnet": 4168930.005797631,
      "HyperEVM": 70982160.0668502,
      "Arbitrum": 560012.5612603555,
      "Unichain": 22498.027329116572
    },
    "byProtocol": {
      "Morpho": 2132675373.6329496,
      "Euler": 12836565.004137252
    },
    "byTier": {
      "Mega (>$500M)": 1607819583.4552197,
      "Large ($100M–500M)": 292880433.5397914,
      "Mid ($25M–100M)": 182961472.43315214,
      "Small ($5M–25M)": 44046513.27067962,
      "Emerging (<$5M)": 17803935.938243818
    }
  },
  "assetColors": {
    "BTC": "var(--orange)",
    "ETH / LST / LRT": "var(--blue)",
    "Stablecoin": "var(--green)",
    "RWA / Credit": "var(--purple)",
    "Pendle / Fixed-term": "var(--yellow)",
    "Altcoin / L1": "var(--red)",
    "Other / Long-tail": "var(--fg-muted)"
  }
};
